project.clj, src/clj/starcity/datomic.clj, src/clj/starcity/datomic/util.clj, src/clj/starcity/models/account.clj, src/clj/starcity/pages/auth.clj, src/clj/starcity/pages/util.clj
=> add authentication validation & messaging

project.clj, src/cljs/starcity/phases/one/sections/basic.cljs, src/cljs/starcity/ui/field_kit.cljs, src/cljs/starcity/util.cljs
=> Issue 38/input validation

resources/datomic/schemas/account.edn, resources/datomic/seed/account.edn, src/clj/starcity/models/account.clj, src/clj/starcity/pages/auth.clj, src/clj/starcity/pages/auth/common.clj, src/clj/starcity/pages/auth/login.clj, src/clj/starcity/pages/auth/signup.clj, src/clj/starcity/server.clj, src/clj/starcity/util.clj
=> Signup additions

project.clj, resources/config/config.edn, src/clj/starcity/config.clj, src/clj/starcity/core.clj, src/clj/starcity/nrepl.clj, src/clj/starcity/server.clj, src/dev/user.clj
=> add proper system configuration

project.clj, resources/config/development.edn, resources/config/production.edn, resources/datomic/schemas/account.edn, resources/datomic/seed/account.edn, src/clj/starcity/core.clj, src/clj/starcity/datomic.clj, src/clj/starcity/logger.clj, src/clj/starcity/middleware.clj, src/clj/starcity/models/account.clj, src/clj/starcity/pages/auth.clj, src/clj/starcity/pages/auth/login.clj, src/clj/starcity/pages/auth/signup.clj, src/clj/starcity/server.clj, src/clj/starcity/services/mailgun.clj, src/dev/user.clj
=> Add activation email & proper signup

project.clj, resources/datomic/schemas/property.edn, resources/datomic/seed/account.edn, resources/datomic/seed/properties.edn, src/clj/starcity/auth.clj, src/clj/starcity/config.clj, src/clj/starcity/datomic.clj, src/clj/starcity/middleware.clj, src/clj/starcity/models/account.clj, src/clj/starcity/models/property.clj, src/clj/starcity/pages/application.clj, src/clj/starcity/pages/auth.clj, src/clj/starcity/pages/auth/login.clj, src/clj/starcity/pages/auth/signup.clj, src/clj/starcity/pages/availability.clj, src/clj/starcity/pages/dashboard.clj, src/clj/starcity/pages/landing.clj, src/clj/starcity/pages/register.clj, src/clj/starcity/router.clj, src/clj/starcity/routes.clj, src/clj/starcity/server.clj
Adds a minimal db-backed UI for availability page, see #66.
=> Issue 66/availability

doc/signup.org, project.clj, src/clj/starcity/pages/application.clj, src/clj/starcity/routes.clj, src/clj/starcity/server.clj, src/dev/devtools.cljs, src/dev/user.clj
=> Issue 74/application ui

resources/public/assets/css/login.css, resources/public/assets/css/signup.css, src/clj/starcity/controllers/auth/login.clj, src/clj/starcity/views/auth/login.clj, src/clj/starcity/views/auth/signup.clj
=> clean up auth views

src/clj/starcity/auth.clj, src/clj/starcity/controllers/application.clj, src/clj/starcity/controllers/application/checks.clj, src/clj/starcity/controllers/auth/login.clj, src/clj/starcity/controllers/auth/signup.clj, src/clj/starcity/controllers/error.clj, src/clj/starcity/middleware.clj, src/clj/starcity/models/account.clj, src/clj/starcity/models/application.clj, src/clj/starcity/models/util.clj, src/clj/starcity/routes.clj, src/clj/starcity/views/application.clj, src/clj/starcity/views/application/checks.clj, src/clj/starcity/views/auth/login.clj, src/clj/starcity/views/error.clj
=> Application gating

resources/public/js/community.js, src/clj/starcity/controllers/application/checks.clj, src/clj/starcity/controllers/application/common.clj, src/clj/starcity/controllers/application/community_fitness.clj, src/clj/starcity/controllers/application/logistics.clj, src/clj/starcity/controllers/application/submit.clj, src/clj/starcity/models/application.clj, src/clj/starcity/routes.clj, src/clj/starcity/views/application/checks.clj, src/clj/starcity/views/application/common.clj, src/clj/starcity/views/application/community_fitness.clj, src/clj/starcity/views/application/logistics.clj, src/clj/starcity/views/application/submit.clj
=> add community fitness and submit skeleton

src/clj/starcity/controllers/application.clj, src/clj/starcity/views/application.clj
=> add different view when application is locked

resources/datomic/schemas/application.edn, src/clj/starcity/controllers/application.clj, src/clj/starcity/views/application.clj
=> add some copy to post-submission views

resources/public/assets/css/application.css, resources/public/js/submit.js, src/clj/starcity/views/application/checks.clj, src/clj/starcity/views/application/submit.clj
=> add content to submit page

resources/public/assets/css/common.css, src/clj/starcity/controllers/privacy.clj, src/clj/starcity/controllers/terms.clj, src/clj/starcity/routes.clj, src/clj/starcity/views/base.clj, src/clj/starcity/views/privacy.clj, src/clj/starcity/views/terms.clj
=> add privacy and terms pages

src/clj/starcity/auth.clj, src/clj/starcity/views/application.clj, src/clj/starcity/views/application/common.clj, src/clj/starcity/views/auth/login.clj, src/clj/starcity/views/auth/signup.clj, src/clj/starcity/views/base.clj, src/clj/starcity/views/base/nav.clj
Close #172 
Close #173 
Close #149
=> redirect to signup

resources/config/config.edn, src/clj/starcity/config.clj, src/clj/starcity/controllers/application/personal.clj, src/clj/starcity/controllers/application/submit.clj, src/clj/starcity/datomic/migrations/initial.clj, src/clj/starcity/datomic/migrations/initial/add_account_schema.clj, src/clj/starcity/datomic/migrations/initial/add_community_safety_schema.clj, src/clj/starcity/datomic/migrations/initial/add_request_status_schema.clj, src/clj/starcity/datomic/migrations/initial/seed_test_accounts.clj, src/clj/starcity/middleware.clj, src/clj/starcity/models/account.clj, src/clj/starcity/models/application.clj, src/clj/starcity/models/community_safety.clj, src/clj/starcity/models/property.clj, src/clj/starcity/models/util.clj, src/clj/starcity/models/util/update.clj, src/clj/starcity/services/community_safety.clj, src/clj/starcity/views/base.clj, src/clj/starcity/views/legal/render.clj
=> Issue 136/community safety

resources/config/config.edn, resources/public/js/main.js, src/clj/starcity/controllers/application/personal.clj, src/clj/starcity/datomic/migrations.clj, src/clj/starcity/logger.clj, src/clj/starcity/models/account.clj, src/clj/starcity/views/application/personal.clj
=> Issue 155/phone number

.gitignore, elm-package.json, elm/Admin.elm, elm/Admin/Application.elm, elm/Admin/Application/Common.elm, elm/Admin/Application/Income.elm, elm/Admin/Applications.elm, elm/Admin/Page.elm, elm/Util.elm, src/clj/starcity/api/admin/applications.clj, src/clj/starcity/api/plaid.clj, src/clj/starcity/controllers/auth/login.clj, src/clj/starcity/datomic/migrations/initial/seed_test_accounts.clj, src/clj/starcity/datomic/migrations/seed_test_applications_8_4_16.clj, src/clj/starcity/models/account.clj, src/clj/starcity/services/plaid.clj
=> Issue 250/admin dashboard

elm/Admin/Application/Income.elm
* rewrite migrations logic to be far simpler
* add sample application in for development
* remove nil-valued keys before transacting
* add logic for pulling application info
* working routing & simple list view
* add working (but incomplete) admin dashboard
* remove old css, ignore generated css
* remove from source control
* remove stale build script, add asset build script
* fixed directory structure
* fix initialization issue with migrations
* better logging
* remove sensitive info from logs
* add informational admin dashboard
=> Variety of dashboard bugfixes

resources/config/production.edn, src/clj/starcity/api/admin/applications.clj, src/clj/starcity/controllers/application.clj, src/clj/starcity/controllers/application/submit.clj, src/clj/starcity/controllers/auth/signup.clj, src/clj/starcity/datomic/migrations/initial/seed_test_accounts.clj, src/clj/starcity/models/account.clj, src/clj/starcity/routes.clj, src/clj/starcity/server.clj, src/clj/starcity/services/mailgun.clj, src/clj/starcity/services/slack.clj, src/clj/starcity/views/application.clj, src/clj/starcity/views/auth/login.clj, src/clj/starcity/views/auth/signup.clj
=> Issue 246/slack

resources/config/config.edn, src/clj/starcity/server.clj
=> Issue 222/persist sessions

src/clj/starcity/datomic/migrations.clj, src/clj/starcity/datomic/migrations/add_member_application_status_11_15_16.clj
=> fix seeding issue

project.clj, src/clj/starcity/models/security_deposit.clj, src/cljs/onboarding/db.cljs, src/cljs/onboarding/prompts/deposit/bank.cljs, src/cljs/onboarding/prompts/review.cljs, src/cljs/onboarding/prompts/services/customize.cljs, src/cljs/onboarding/prompts/services/moving.cljs, style/sass/partials/_navbar.sass
=> onboarding improvements

src/clj/starcity/observers/slack.clj
=> change sales-related notifications to #crm from #community

src/clj/starcity/models/account.clj, src/clj/starcity/models/order.clj, src/clj/starcity/observers/slack.clj
=> add premium service notifications after onboarding

env/dev/starcity/seed.clj, project.clj, src/clj/starcity/api/admin/accounts.clj, src/clj/starcity/models/account.clj, src/clj/starcity/models/approval.clj, src/clj/starcity/models/member_license.clj, src/clj/starcity/models/property.clj, src/clj/starcity/models/rent_payment.clj, src/clj/starcity/models/security_deposit.clj, src/clj/starcity/models/unit.clj, src/clj/starcity/observers/cmds.clj, src/clj/starcity/observers/cmds/stripe.clj, src/clj/starcity/observers/slack.clj, src/cljs/admin/accounts/events.cljs, src/cljs/admin/accounts/subs.cljs, src/cljs/admin/accounts/views/entry/application.cljs, src/cljs/admin/home/views.cljs
=> Fix issues with timezones

project.clj, src/clj/starcity/api/onboarding.clj, src/clj/starcity/models/order.clj, src/clj/starcity/models/unit.clj
- add order placement logic
- fix bug with unhandled stripe events
=> Release 1.9.1

project.clj
Also excluded Datomic Pro from the reactor dependency
=> Bump version to 1.10.1-SNAPSHOT

env/dev/user.clj, package-lock.json, package.json, resources/public/js/main.js, resources/templates/landing.html, style/sass/partials/public/_slick.scss, style/sass/public.scss
Would adding the function go! to reset be appropriate?
=> Video carousel + go! function
